name: gcbad_dart
description: GoCardless Bank Account Data client.
version: 1.0.0
# repository: https://github.com/lezli01/gcbad_dart

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
  puppeteer: ^3.6.0
